import { z } from 'zod';

export const ProductSchema = z.object({
  name: z.string().min(2, "Name is too short"),
  description: z.string().min(10, "Description must be detailed for the AI"),
  price: z.number().positive(),
  category: z.string(),
  image: z.string().url(), // Cloudinary URL
  
  // For Semantic Search & AI Agent
  embeddings: z.array(z.number()).optional(), // Generated by OpenAI/Gemini
  tags: z.array(z.string()).default([]), // e.g., ["spicy", "keto", "vegan"]
  pros: z.array(z.string()).default([]),
  cons: z.array(z.string()).default([]),
  
  // Metadata for Vision/AR
  isAvailable: z.boolean().default(true),
  preparationTime: z.number().optional(), // In minutes
});

export type Product = z.infer<typeof ProductSchema>;